ALTER TABLE auto_post ADD COLUMN car_id int REFERENCES car(id);

ALTER TABLE auto_user ADD CONSTRAINT login_unique UNIQUE (login);

ALTER TABLE auto_post ADD COLUMN sold BOOLEAN;

ALTER TABLE car ADD COLUMN  body TEXT;

ALTER TABLE car ADD COLUMN color TEXT;